 MATCH (node14:_Identifiable {uuid: "d9262ce3-7847-4263-aa18-a27bcdc1f642"})
                MERGE (node1756:_Identifiable {uuid: "789be2cd-4f87-4f43-a865-18f0ae1293db"})
                ON CREATE SET node1756:Functionality
                ON CREATE SET node1756 += {name: "Schema Editing"}
MERGE (node1756)-[rel5439: AUTOGENERATED_FROM {uuid: "c5f20f3e-8a4d-48f1-adc6-a12116ea455f"}]->(node14)
ON CREATE SET rel5439 += {}
