CREATE CONSTRAINT ON (n:Category) ASSERT n.categoryID IS UNIQUE;

CREATE CONSTRAINT ON (n:Customer) ASSERT n.customerID IS UNIQUE;

CREATE CONSTRAINT ON (n:Order) ASSERT n.orderID IS UNIQUE;

CREATE CONSTRAINT ON (n:Product) ASSERT n.productID IS UNIQUE;

CREATE CONSTRAINT ON (n:Supplier) ASSERT n.supplierID IS UNIQUE;

CREATE CONSTRAINT ON (n:Employee) ASSERT n.employeeID IS UNIQUE;
